definitions:
  api.ApiResponse:
    properties:
      body: {}
      error: {}
      success:
        type: boolean
    type: object
  db.TaskStatus:
    enum:
    - IN_PROGRESS
    - COMPLETED
    - EXPIRED
    type: string
    x-enum-varnames:
    - TaskStatusInProgress
    - TaskStatusCompleted
    - TaskStatusExpired
  db.TaskType:
    enum:
    - CODE_GENERATION
    - DIALOGUE
    - TEXT_TO_IMAGE
    type: string
    x-enum-varnames:
    - TaskTypeCodeGeneration
    - TaskTypeDialogue
    - TaskTypeTextToImage
  miner.MinerApplicationRequest:
    properties:
      email:
        type: string
      hotkey:
        type: string
      organisationName:
        type: string
    type: object
  miner.MinerInfoResponse:
    properties:
      minerId:
        type: string
      subscriptionKey:
        type: string
    type: object
  task.Pagination:
    properties:
      pageNumber:
        type: integer
      pageSize:
        type: integer
      totalItems:
        type: integer
      totalPages:
        type: integer
    type: object
  task.Result:
    properties:
      type:
        type: string
      value: {}
    type: object
  task.SubmitTaskResultRequest:
    properties:
      resultData:
        items:
          $ref: '#/definitions/task.Result'
        type: array
    type: object
  task.SubmitTaskResultResponse:
    properties:
      numResults:
        type: integer
    type: object
  task.TaskPagination:
    properties:
      pagination:
        $ref: '#/definitions/task.Pagination'
      tasks:
        items:
          $ref: '#/definitions/task.TaskPaginationResponse'
        type: array
    type: object
  task.TaskPaginationResponse:
    properties:
      body:
        type: string
      expireAt:
        type: string
      isCompletedByWorker:
        type: boolean
      maxResults:
        type: integer
      numCriteria:
        type: integer
      numResults:
        type: integer
      status:
        $ref: '#/definitions/db.TaskStatus'
      taskData: {}
      taskId:
        type: string
      title:
        type: string
      type:
        $ref: '#/definitions/db.TaskType'
    type: object
  task.TaskResponse:
    properties:
      body:
        type: string
      expireAt:
        type: string
      maxResults:
        type: integer
      numCriteria:
        type: integer
      numResults:
        type: integer
      status:
        $ref: '#/definitions/db.TaskStatus'
      taskData: {}
      taskId:
        type: string
      title:
        type: string
      type:
        $ref: '#/definitions/db.TaskType'
    type: object
  worker.DisableMinerRequest:
    properties:
      minerSubscriptionKey:
        type: string
      toDisable:
        type: boolean
    type: object
  worker.DisableSucessResponse:
    properties:
      message:
        type: string
    type: object
  worker.DisableWorkerRequest:
    properties:
      toDisable:
        type: boolean
      workerId:
        type: string
    type: object
  worker.GenerateNonceResponse:
    properties:
      nonce:
        type: string
    type: object
  worker.ListWorkerPartnersResponse:
    properties:
      partners:
        items:
          $ref: '#/definitions/worker.WorkerPartner'
        type: array
    type: object
  worker.UpdateWorkerPartnerRequest:
    properties:
      minerSubscriptionKey:
        type: string
      name:
        type: string
      newMinerSubscriptionKey:
        type: string
    type: object
  worker.UpdateWorkerPartnerResponse:
    properties:
      workerPartner:
        $ref: '#/definitions/worker.WorkerPartner'
    type: object
  worker.WorkerLoginRequest:
    properties:
      chainId:
        type: string
      message:
        type: string
      signature:
        type: string
      timestamp:
        type: string
      walletAddress:
        type: string
    type: object
  worker.WorkerLoginSuccessResp:
    properties:
      token: {}
    type: object
  worker.WorkerPartner:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      subscriptionKey:
        type: string
    type: object
  worker.WorkerPartnerCreateRequest:
    properties:
      minerSubscriptionKey:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/{address}:
    get:
      consumes:
      - application/json
      description: Generate a nonce for a given wallet address
      parameters:
      - description: Wallet address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Nonce generated successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/worker.GenerateNonceResponse'
              type: object
        "400":
          description: Address parameter is required
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "500":
          description: Failed to store nonce
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Generate nonce
      tags:
      - Authentication
  /api/v1/miner/info/{hotkey}:
    get:
      consumes:
      - application/json
      description: Retrieve miner information using the miner's user context
      parameters:
      - description: Hot Key
        in: path
        name: hotkey
        required: true
        type: string
      - description: API Key
        in: header
        name: x-api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Miner information retrieved successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/miner.MinerInfoResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Get miner information
      tags:
      - Miner
  /api/v1/miner/miner-application:
    post:
      consumes:
      - application/json
      description: Submit an application for a miner API key and subscription key
        by providing the necessary details
      parameters:
      - description: Request body containing the miner application details (organisationName
          is optional)
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/miner.MinerApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Application submitted successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  type: string
              type: object
        "400":
          description: Invalid request body or parameters
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Apply for a miner API key and subscription key
      tags:
      - Miner
  /api/v1/miner/partner/disable:
    put:
      consumes:
      - application/json
      description: Disable a worker by providing the worker's ID and a disable flag
      parameters:
      - description: API Key
        in: header
        name: x-api-key
        required: true
        type: string
      - description: Request body containing the worker ID and disable flag
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/worker.DisableWorkerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Worker disabled successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/worker.DisableSucessResponse'
              type: object
        "500":
          description: Internal server error - failed to disable worker partner
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Disable worker by miner
      tags:
      - Worker Partner
  /api/v1/partner/edit:
    put:
      consumes:
      - application/json
      description: Update the subscription key and name of a worker partner
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body containing the details to update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/worker.UpdateWorkerPartnerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated worker partner
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/worker.UpdateWorkerPartnerResponse'
              type: object
        "500":
          description: Internal server error - failed to update worker partner
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Update worker partner details
      tags:
      - Worker Partner
  /api/v1/tasks:
    get:
      consumes:
      - application/json
      description: Get a paginated list of tasks based on the specified parameters
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Comma-separated list of task types (e.g., CODE_GENERATION,TEXT_TO_IMAGE,DIALOGUE).
          Use 'All' to include all types.
        in: query
        name: task
        required: true
        type: string
      - description: Page number (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of tasks per page (default is 10)
        in: query
        name: limit
        type: integer
      - description: Sort field (default is createdAt)
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved task pagination response
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/task.TaskPagination'
              type: object
        "500":
          description: "Internal server error - success is always false\"\t{ \"success\":
            false, \"error\": \"Internal server error\", \"body\": null }"
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Retrieve tasks by pagination
      tags:
      - Tasks
  /api/v1/tasks/{task-id}:
    get:
      consumes:
      - application/json
      description: Get details of a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: task-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved task response
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/task.TaskResponse'
              type: object
        "404":
          description: Task not found, error message wrapped in ApiResponse structure
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                error:
                  type: string
              type: object
        "500":
          description: Internal server error, error message wrapped in ApiResponse
            structure
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                error:
                  type: string
              type: object
      summary: Retrieve task by ID
      tags:
      - Tasks
  /api/v1/tasks/submit-result/{task-id}:
    put:
      consumes:
      - application/json
      description: Submit the result of a task
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task ID
        in: path
        name: task-id
        required: true
        type: string
      - description: Request body containing the task result data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/task.SubmitTaskResultRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Task result submitted successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/task.SubmitTaskResultResponse'
              type: object
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "404":
          description: Task not found
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Submit task result
      tags:
      - Tasks
  /api/v1/worker/login/auth:
    post:
      consumes:
      - application/json
      description: Log in a worker by providing their wallet address, chain ID, message,
        signature, and timestamp
      parameters:
      - description: Request body containing the worker login details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/worker.WorkerLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Worker logged in successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/worker.WorkerLoginSuccessResp'
              type: object
        "400":
          description: Invalid wallet address or chain ID
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "500":
          description: Failed to create worker
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Worker login
      tags:
      - Authentication
  /api/v1/worker/partner:
    post:
      consumes:
      - application/json
      description: Create a partnership between a worker and a miner
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body containing the name and miner subscription key
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/worker.WorkerPartnerCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created worker-miner partnership
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Create worker-miner partnership
      tags:
      - Worker Partner
  /api/v1/worker/partner/disable:
    put:
      consumes:
      - application/json
      description: Disable a miner by providing the worker's subscription key and
        a disable flag
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body containing the miner subscription key and disable
          flag
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/worker.DisableMinerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Miner disabled successfully
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/worker.DisableSucessResponse'
              type: object
        "500":
          description: Internal server error - failed to disable worker partner
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Disable miner by worker
      tags:
      - Worker Partner
  /api/v1/worker/partner/list:
    get:
      consumes:
      - application/json
      description: Retrieve a list of partners for the authenticated worker
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved worker partners
          schema:
            allOf:
            - $ref: '#/definitions/api.ApiResponse'
            - properties:
                body:
                  $ref: '#/definitions/worker.ListWorkerPartnersResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "404":
          description: Worker not found
          schema:
            $ref: '#/definitions/api.ApiResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/api.ApiResponse'
      summary: Get worker partner list
      tags:
      - Worker Partner
swagger: "2.0"
